/*
 * DIO_Configurations.h
 *
 *  Created on: Aug 2, 2023
 *      Author: Hesham Yasser
 */

#ifndef INCLUDE_MCAL_DIO_DIO_CONFIGURATIONS_H_
#define INCLUDE_MCAL_DIO_DIO_CONFIGURATIONS_H_

/*Pin Directions
 	* OUTPUT_PIN
 	* INPUT_PIN
 */

//PORTA Directions
#define PINA0_DIR		INPUT_PIN
#define PINA1_DIR		INPUT_PIN
#define PINA2_DIR		INPUT_PIN
#define PINA3_DIR		INPUT_PIN
#define PINA4_DIR		OUTPUT_PIN
#define PINA5_DIR		OUTPUT_PIN
#define PINA6_DIR		OUTPUT_PIN
#define PINA7_DIR		OUTPUT_PIN
//PORTB Directions
#define PINB0_DIR		OUTPUT_PIN
#define PINB1_DIR		OUTPUT_PIN
#define PINB2_DIR		OUTPUT_PIN
#define PINB3_DIR		OUTPUT_PIN
#define PINB4_DIR		OUTPUT_PIN
#define PINB5_DIR		OUTPUT_PIN
#define PINB6_DIR		OUTPUT_PIN
#define PINB7_DIR		OUTPUT_PIN
//PORTC Directions
#define PINC0_DIR		OUTPUT_PIN
#define PINC1_DIR		OUTPUT_PIN
#define PINC2_DIR		OUTPUT_PIN
#define PINC3_DIR		OUTPUT_PIN
#define PINC4_DIR		OUTPUT_PIN
#define PINC5_DIR		OUTPUT_PIN
#define PINC6_DIR		OUTPUT_PIN
#define PINC7_DIR		OUTPUT_PIN
//PORTD Directions
#define PIND0_DIR		OUTPUT_PIN
#define PIND1_DIR		OUTPUT_PIN
#define PIND2_DIR		OUTPUT_PIN
#define PIND3_DIR		OUTPUT_PIN
#define PIND4_DIR		OUTPUT_PIN
#define PIND5_DIR		OUTPUT_PIN
#define PIND6_DIR		OUTPUT_PIN
#define PIND7_DIR		OUTPUT_PIN


/*Pin Values :-
 	* PIN_HIGH
 	* PIN_LOW
 */
//PORTA Values
#define PINA0_VAL		PIN_HIGH
#define PINA1_VAL		PIN_HIGH
#define PINA2_VAL		PIN_HIGH
#define PINA3_VAL		PIN_HIGH
#define PINA4_VAL		PIN_HIGH
#define PINA5_VAL		PIN_HIGH
#define PINA6_VAL		PIN_HIGH
#define PINA7_VAL		PIN_HIGH
//PORTB Values
#define PINB0_VAL		PIN_HIGH
#define PINB1_VAL		PIN_HIGH
#define PINB2_VAL		PIN_HIGH
#define PINB3_VAL		PIN_HIGH
#define PINB4_VAL		PIN_HIGH
#define PINB5_VAL		PIN_HIGH
#define PINB6_VAL		PIN_HIGH
#define PINB7_VAL		PIN_HIGH
//PORTC Values
#define PINC0_VAL		PIN_HIGH
#define PINC1_VAL		PIN_HIGH
#define PINC2_VAL		PIN_HIGH
#define PINC3_VAL		PIN_HIGH
#define PINC4_VAL		PIN_HIGH
#define PINC5_VAL		PIN_HIGH
#define PINC6_VAL		PIN_HIGH
#define PINC7_VAL		PIN_HIGH
//PORTD Values
#define PIND0_VAL		PIN_HIGH
#define PIND1_VAL		PIN_HIGH
#define PIND2_VAL		PIN_HIGH
#define PIND3_VAL		PIN_HIGH
#define PIND4_VAL		PIN_HIGH
#define PIND5_VAL		PIN_HIGH
#define PIND6_VAL		PIN_HIGH
#define PIND7_VAL		PIN_HIGH


#endif /* INCLUDE_MCAL_DIO_DIO_CONFIGURATIONS_H_ */
